settings:
  title: 'Status Page'
  url: 'https://status.bysshe.co.uk/*' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Bysshe IT Website # unique identifier
    name: web.bysshe.co.uk
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://web.bysshe.co.uk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Bysshe VPN
    name: vpn.bysshe.co.uk
    description: 'Built for anything connected to the Internet.'
    url: 'https://vpn.bysshe.co.uk'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true # allows the title to be a link, default=true

  - id: Plex # unique identifier
    name: plex.bysshe.co.uk
    description: 'This status page.' # default=empty
    url: 'https://plex.bysshe.co.uk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Jules-Driving-School # unique identifier
    name: Jules Driving School Website
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://learnwithjules.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: Fog
    name: fog.bysshe.co.uk
    description: 'Built for anything connected to the Internet.'
    url: 'https://fog.bysshe.co.uk'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Remote Apps # unique identifier
    name: remote.bysshe.co.uk
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://remote.bysshe.co.uk/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: cloudflare-com
    name: The Cloudflare Blog
    url: 'https://www.cloudflare.com/'
    method: GET
    expectStatus: 200
