name = "statuspage"
workers_dev = true
account_id = "4d0c2f790a9c822bf8627c782d9eb866"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2050-09-14"

[build]
command = "npm run build"
#account_id = "4d0c2f790a9c822bf8627c782d9eb866"
#type = "webpack"
#webpack_config = "node_modules/flareact/webpack"

#[[hyperdrive]]
#binding = "HYPERDRIVE"
id = "statuspage"

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "out"
entry-point = 'https://4d0c2f790a9c822bf8627c782d9eb866.r2.cloudflarestorage.com/statuspage/'

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="bysshe.co.uk"
#route="status.bysshe.co.uk/"


